### ISSUE TITLE
Not working with Zenbook 14 Flip OLED (UN5401, AMD Ryzen 5000 Series)

### ISSUE THREAD

**Issue by Shaurya-Kalia** [asus-linux-drivers/asus-fliplock-driver#1]
Is it supposed to work with this device? I installed it in manjaro as per the instructions, and it installed successfully and even enabled the service. But rotating the screen is still not disabling touchpad and keyboard.

Running the troubleshooting step shows the following:
DEBUG:Asus fliplock:Detect wmi hotkeys from N: Name="Asus WMI hotkeys"
DEBUG:Asus fliplock:Set wmi hotkeys id 4 from H: Handlers=kbd event4 rfkill

I rotated the screen too to see any additional log was generated but this was it. Please inform if I should provide any more info if necessary

**Comment by ldrahnik** [comment]
I am sorry that I reply late. Can you please try run this command and do a flip with a laptop, you should see:

```
$sudo libinput debug-events
...
-event25  DEVICE_ADDED     Intel HID switches                seat0 default group10 cap:S
-event4   DEVICE_ADDED     Asus WMI hotkeys                  seat0 default group11 cap:k
...
-event25  SWITCH_TOGGLE    +0.000s	switch tablet-mode state 1
-event4   KEYBOARD_KEY     +0.000s	KEY_PROG2 (149) pressed
 event4   KEYBOARD_KEY     +0.000s	KEY_PROG2 (149) released
-event25  SWITCH_TOGGLE    +1.352s	switch tablet-mode state 0
-event4   KEYBOARD_KEY     +1.352s	KEY_PROG2 (149) pressed
 event4   KEYBOARD_KEY     +1.352s	KEY_PROG2 (149) released
```

In my case after the laptop starts first is during flip sent only `KEY_PROG2` pressed and immediately released, then is added device `Intel HID switches` and i see even `switch tablet-mode state 0/1` messages. My code should solve both cases.

**Comment by Shaurya-Kalia** [comment]
```
libinput debug-events                                                                                                                                                                           ✔ 
-event3   DEVICE_ADDED            Video Bus                         seat0 default group1  cap:k
-event0   DEVICE_ADDED            Lid Switch                        seat0 default group2  cap:S
-event1   DEVICE_ADDED            Power Button                      seat0 default group3  cap:k
-event5   DEVICE_ADDED            USB2.0 HD UVC WebCam: USB2.0 HD   seat0 default group4  cap:k
-event10  DEVICE_ADDED            ELAN9008:00 04F3:2E36             seat0 default group5  cap:t  size 300x184mm ntouches 10 calib
-event13  DEVICE_ADDED            ELAN9008:00 04F3:2E36 Stylus      seat0 default group5  cap:T  size 300x190mm calib
-event6   DEVICE_ADDED            ASUE140D:00 04F3:31B9 Mouse       seat0 default group6  cap:p left scroll-nat scroll-button
-event15  DEVICE_ADDED            ASUE140D:00 04F3:31B9 Touchpad    seat0 default group6  cap:pg  size 125x72mm tap(dl off) left scroll-nat scroll-2fg-edge click-buttonareas-clickfinger dwt-on dwtp-on
-event16  DEVICE_ADDED            ASUE140D:00 04F3:31B9 Keyboard    seat0 default group6  cap:k
-event4   DEVICE_ADDED            Asus WMI hotkeys                  seat0 default group7  cap:k
-event2   DEVICE_ADDED            AT Translated Set 2 keyboard      seat0 default group8  cap:k
```
This was the result in my case. All these entries were populated as soon as I ran the command. I flipped the laptop twice completely but nothing new was registered

**Comment by ldrahnik** [comment]
So we figured out that is not a problem with this driver.

So when you finish the flip, you can write on the keyboard/use touchpad on the other side?! Dangerous. For me, with Elementary OS 6.1 Jólnir by default is disabled with a flip touchpad and even keyboard. Everything else I add by myself via this script.

So you have to figure out why your `Asus WMI hotkeys` does not send `KEY_PROG2` or why is not added `Intel HID switches` with first flip. Atleast one you have to solve. What I recommend? Try clean installation, try another distribution if it works (I recommend Ubuntu, should be enough live USB because you have almost the same laptop as me and it works for me), upgrading Kernel might help (maybe your system have missing any patch), I had it working on `5.13` and now I upgraded to `5.18`.

Good luck!

EDIT: Also could help instead of flip try to move opened a laptop to the sides, like a boat on the ocean. It also sends me these events, probably as protection or sensor do not know that is not a flip, idk.

**Comment by Shaurya-Kalia** [comment]
>why is not added Intel HID switches with first flip

I have the amd model. Should it also show Intel HID switches?

**Comment by ldrahnik** [comment]
I would like to be more helpful but I do not know. Did you try what I proposed?

**Comment by Shaurya-Kalia** [comment]
>I would like to be more helpful but I do not know. Did you try what I proposed?

I had linux mint iso but it wasn't booting. So I have downloaded ubuntu iso. I will try when i get home and update in few hours

**Comment by Shaurya-Kalia** [comment]
Okay, i tried in ubuntu live iso. It shows the same behaviour as before. In windows 11, even rotating to around 210° switches off keyboard and mouse. In linux, keyboard and mouse remain operational the entire time, even the backlight doesn't switch off and there is no new event in libinput debug-events when rotating to even full circle. I am guessing that the sensor in AMD version isn't yet added to kernel?

**Comment by ldrahnik** [comment]
If you will find a reason why device `Intel HID switches` is missing and whether exists a replacement, post a message here. If this driver would not work without any changes with your newly found solution, feel free to make a pull request.
