### ISSUE TITLE
Doesn't work on zenbook 14.

### ISSUE THREAD

**Issue by Tima32** [asus-linux-drivers/asus-fliplock-driver#10]
Nothing happens after installing the driver. The numpad does not turn on and the keyboard does not turn off. I have the amd version.
Log:
`DEBUG:Asus fliplock:Detect wmi hotkeys from N: Name="Asus WMI hotkeys"
DEBUG:Asus fliplock:Set wmi hotkeys id 14 from H: Handlers=rfkill kbd event14`

**Comment by ldrahnik** [comment]
@Tima32 Unfortunatelly looks like AMD usually do not sent fliplock event / programmed keys. Do not have AMD laptop version so I can not be more helpful. But your are not first, try look to other issues and please let me know if you fixed your problem. In case I could hook in code of this driver to some other events specially for AMD version, let me know too. Closing as it is not issue of this driver.
