### ISSUE TITLE
Keyboard not working on ASUS Expertbook

### ISSUE THREAD

**Issue by Geras1mleo** [asus-linux-drivers/asus-fliplock-driver#12]
Hi there!

Me again, so I tried this driver out for my ASUS Expertbook and it partially (led switches etc) worked but my keyboard still doesn't work :cry:... 

See: https://github.com/asus-linux-drivers/asus-accel-tablet-mode-driver/issues/4

Below some debug logs I have used to troubleshoot but no result...

Logs are for these steps:
1: uninstall driver
2: run libinput
3: run python script
4: flip keyboard behind the screen and back to normal

For the reference: after flips I click a few times on Super/CapsLock/Space and other keys but no events are visible in libinput... BUT! **some** Fn keys work just fine, such as `KEY_BRIGHTNESSDOWN` and `KEY_BRIGHTNESSUP`...

![image](https://github.com/asus-linux-drivers/asus-fliplock-driver/assets/67554762/72129e89-af1b-47e1-9085-fcef90822e35)

**I would really appreciate some help from anyone!**

Is it another kernel bug or am I missing something?

Thank you anyways for your time!

Cheers, Sviatoslav

**Comment by ldrahnik** [comment]
@Geras1mleo Hello there, I am sorry for late response. Still does not work? Or solved, what was the problem? In case keyboard was not working before the flip it looks like problem unrelated to this fliplock driver? Can be reopened.

**Comment by Geras1mleo** [comment]
It was indeed a kernel bug. See the patch below:

https://lore.kernel.org/linux-acpi/52cf0eab-dbbd-4f12-b100-c7db1daea442@gmail.com/T/#u

Anyway, thank you for your time!

Greetings Sviatoslav
