### ISSUE TITLE
Fliplock driver permission error

### ISSUE THREAD

**Issue by sudoMakeThisSecure** [asus-linux-drivers/asus-fliplock-driver#13]
I installed it with sudo ./install.sh, as you said to and have your accel driver installed too, which is sending it tablet mode correctly i think. It is certinally flipping the screen anyway.
I think its something to do with the device that im using not being the defult one for you. I have a Asus vivobook S14 flip (TN3402Y non OLED)

The log is:
m@Ms-Vivobook:~/asus-fliplock-driver$ LOG=DEBUG sudo -E ./asus_fliplock.py "default"
DEBUG:Asus fliplock:Detect wmi hotkeys from N: Name="Asus WMI accel tablet mode"
DEBUG:Asus fliplock:Set wmi hotkeys id 19 from H: Handlers=kbd event19
DEBUG:Asus fliplock:InputEvent(EV_KEY, KEY_PROG2, 1)
3
0
0
0
0
0
tee: /sys/kernel/debug/asus-nb-wmi/dev_id: Operation not permitted
tee: /sys/kernel/debug/asus-nb-wmi/dev_id: Operation not permitted
DEBUG:Asus fliplock:InputEvent(EV_SYN, SYN_REPORT, 0)
DEBUG:Asus fliplock:InputEvent(EV_KEY, KEY_PROG2, 0)
DEBUG:Asus fliplock:InputEvent(EV_SYN, SYN_REPORT, 0)
DEBUG:Asus fliplock:InputEvent(EV_SW, SW_TABLET_MODE, 1)
DEBUG:Asus fliplock:InputEvent(EV_SYN, SYN_REPORT, 0)
DEBUG:Asus fliplock:InputEvent(EV_KEY, KEY_PROG2, 1)
3
0
0
DEBUG:Asus fliplock:InputEvent(EV_SYN, SYN_REPORT, 0)
DEBUG:Asus fliplock:InputEvent(EV_KEY, KEY_PROG2, 0)
DEBUG:Asus fliplock:InputEvent(EV_SYN, SYN_REPORT, 0)
DEBUG:Asus fliplock:InputEvent(EV_SW, SW_TABLET_MODE, 0)
DEBUG:Asus fliplock:InputEvent(EV_SYN, SYN_REPORT, 0)
DEBUG:Asus fliplock:InputEvent(EV_KEY, KEY_PROG2, 1)
0
0
0
0
0
0
tee: /sys/kernel/debug/asus-nb-wmi/dev_id: Operation not permitted
tee: /sys/kernel/debug/asus-nb-wmi/dev_id: Operation not permitted
DEBUG:Asus fliplock:InputEvent(EV_SYN, SYN_REPORT, 0)
DEBUG:Asus fliplock:InputEvent(EV_KEY, KEY_PROG2, 0)
DEBUG:Asus fliplock:InputEvent(EV_SYN, SYN_REPORT, 0)
DEBUG:Asus fliplock:InputEvent(EV_SW, SW_TABLET_MODE, 1)
DEBUG:Asus fliplock:InputEvent(EV_SYN, SYN_REPORT, 0)
DEBUG:Asus fliplock:InputEvent(EV_KEY, KEY_PROG2, 1)
0
0
0

**Comment by ldrahnik** [comment]
Hi @Asdf1qaz,
yes, the default layout (primarily created for my laptop ZenBook UP5401EA and as the example of usage but can fully or partially work for other models aswell) uses `debugfs`. So, you have to have mounted `debugfs` to `/sys/kernel/debug/asus-nb-wmi/`, that means is required have responsible kernel modules `asus-wmi and asus-nb-wmi` installed ([requirements in Readme.md](https://github.com/asus-linux-drivers/asus-fliplock-driver#requirements)). Then check permissions for root, me:

```
ldrahnik@Zenbook-UP5401EA:~$ sudo -s
root@Zenbook-UP5401EA:/sys/kernel/debug/asus-nb-wmi# ls -la
drwxr-xr-x  2 root root 0 Jul 17 06:50 .
drwx------ 61 root root 0 Jul 17 06:50 ..
-r--r--r--  1 root root 0 Jul 17 06:50 call
-rw-r--r--  1 root root 0 Jul 17 17:06 ctrl_param
-rw-r--r--  1 root root 0 Jul 17 17:06 dev_id
-r--r--r--  1 root root 0 Jul 17 06:50 devs
-r--r--r--  1 root root 0 Jul 17 06:50 dsts
-rw-r--r--  1 root root 0 Jul 17 06:50 method_id
```

You can check the error has gone with:

```
$ echo '0x60079' | sudo tee '/sys/kernel/debug/asus-nb-wmi/dev_id'
```

**Comment by ldrahnik** [comment]
Can be reopened.
