### ISSUE TITLE
It doesn't work on Asus Zenbook Flip 14 UN5401Q (AMD)

### ISSUE THREAD

**Issue by Mark12870** [asus-linux-drivers/asus-fliplock-driver#3]
Device: Asus Zenbook Flip 14 UN5401Q (ASUSTeK COMPUTER INC. Zenbook UN5401QAB_UN5401QA)
OS: Ubuntu 22.04.1 LTS

When I flip the device, nothing happens.

Debug log:
```
marek@marek-zenbook:~/Downloads/asus-fliplock-driver-master$ LOG=DEBUG sudo -E ./asus_fliplock.py
[sudo] password for marek: 
DEBUG:Asus fliplock:Detect wmi hotkeys from N: Name="Asus WMI hotkeys"
DEBUG:Asus fliplock:Set wmi hotkeys id 4 from H: Handlers=rfkill kbd event4
```

**Comment by ldrahnik** [comment]
Hi, thank you for creating an issue. 

Can you please run this command `sudo libinput debug-events` and do a flip with your laptop? Post the result here. You should see this as me (this driver reacts to these events):

```
$ sudo libinput debug-events
...
-event4   DEVICE_ADDED     Asus WMI hotkeys                  seat0 default group11 cap:k
...
-event4   KEYBOARD_KEY     +0.623s	KEY_PROG2 (149) pressed
 event4   KEYBOARD_KEY     +0.623s	KEY_PROG2 (149) released
-event29  DEVICE_ADDED     Intel HID switches                seat0 default group16 cap:S
 event29  SWITCH_TOGGLE    +0.722s	switch tablet-mode state 1
-event29  SWITCH_TOGGLE    +1.174s	switch tablet-mode state 0
-event4   KEYBOARD_KEY     +1.175s	KEY_PROG2 (149) pressed
 event4   KEYBOARD_KEY     +1.175s	KEY_PROG2 (149) released
...
```

**Comment by Mark12870** [comment]
Ye, I was just debugging the problem and it looks like it doesn't emit the event at all. Probably the device is not supported properly in the kernel? I was thinking about this place: https://github.com/torvalds/linux/blob/master/drivers/platform/x86/asus-nb-wmi.c

**Comment by ldrahnik** [comment]
It might be a reason. Do you use intel as me or amd? I already met someone with amd but sorry, do not know if he solved / figured out what was the problem.

**Comment by ldrahnik** [comment]
What you can do is check if the kernel module is installed / supported by your distro (I use Ubuntu 20.04 based distro), and is running without problems. If is amd not your case I recommend you try to enable module by yourself & disable module what your laptop is using atm and I believe it should work. Good luck. Stay in touch!

**Comment by ldrahnik** [comment]
Atm your laptop when is flipped to tablet mode disable at least the keyboard or not?

**Comment by Mark12870** [comment]
I have AMD. It doesn't disable anything.
I think the kernel module is loaded. I see all these inputs:
```
marek@marek-zenbook:~$ ls /dev/input/by-path/
pci-0000:04:00.4-usb-0:2:1.0-event  platform-AMDI0010:03-event-mouse
platform-AMDI0010:00-event          platform-AMDI0010:03-mouse
platform-AMDI0010:00-event-mouse    platform-asus-nb-wmi-event
platform-AMDI0010:00-mouse          platform-i8042-serio-0-event-kbd
platform-AMDI0010:03-event-kbd
```
I think `platform-asus-nb-wmi-event` should be emitting the event.

(And sorry Im answering late, I don't see any notification anywhere)

**Comment by leaha00** [comment]
Hey, did anyone ever get this fixed, I have the same laptop and have this problem?
Thanks

**Comment by beankylla** [comment]
I have a UN5401RA and am dying to see this fixed! 
If there is anything i can do to help, glad to do it! Fedora 38 under the hood here.
Thanks a lot for the touchpad driver btw works like a charm!

**Comment by ldrahnik** [comment]
@beankylla Hello there :)

> Thanks a lot for the touchpad driver btw works like a charm!

Glad to hear that, put a star if you like and do not hesitate to create any issue in case you face something.

Please try to run this command `$ sudo acpi_listen` and then flip laptop. Do you see as output any row which contain something like `video/tabletmode`?

**Comment by ldrahnik** [comment]
@beankylla ping

In my case I see:

```
$ sudo acpi_listen
[sudo] password for ldrahnik:          
 video/tabletmode TBLT 0000008A 00000001 # flip to tablet mode
 ...
 video/tabletmode TBLT 0000008A 00000000 # flip back to laptop mode
 ...
```

What do you see on AMD device?

**Comment by beankylla** [comment]
Hi!

nope nothing happens :(
absolutely no feedback / line stay emtpy

**Comment by ldrahnik** [comment]
@beankylla Try `$ sudo libinput debug-events`, do you receive any events during switching your laptop to tablet mode and back? (KEY_F22/F23 for example)

**Comment by beankylla** [comment]
@ldrahnik  nope not if i don't accidently touche screen or keyboard, just tried again ^^'

edit: i just tried again with Fedora 39 and no dice. even kernel 6.5.10 does not seem to have what we need ^^'

**Comment by Esras** [comment]
I've got similar issues to what's described here, the output of `sudo libinput debug-events` gets me:

```
-event14  DEVICE_ADDED            Video Bus                         seat0 default group1  cap:k
-event0   DEVICE_ADDED            Lid Switch                        seat0 default group2  cap:S
-event1   DEVICE_ADDED            Power Button                      seat0 default group3  cap:k
-event7   DEVICE_ADDED            ELAN9008:00 04F3:4065 Stylus      seat0 default group4  cap:T  size 300x190mm calib
-event4   DEVICE_ADDED            ELAN9008:00 04F3:4065             seat0 default group4  cap:t  size 312x191mm ntouches 10 calib
-event11  DEVICE_ADDED            ASUE140D:00 04F3:31B9 Mouse       seat0 default group5  cap:p left scroll-nat scroll-button
-event12  DEVICE_ADDED            ASUE140D:00 04F3:31B9 Touchpad    seat0 default group5  cap:pg  size 129x72mm tap(dl off) left scroll-nat scroll-2fg-edge click-buttonareas-clickfinger dwt-on dwtp-on
-event13  DEVICE_ADDED            ASUE140D:00 04F3:31B9 Keyboard    seat0 default group5  cap:k
-event15  DEVICE_ADDED            Asus WMI hotkeys                  seat0 default group6  cap:k
-event2   DEVICE_ADDED            AT Translated Set 2 keyboard      seat0 default group7  cap:k
 event2   KEYBOARD_KEY            +0.000s	*** (-1) pressed
 event2   KEYBOARD_KEY            +0.146s	*** (-1) pressed
```

This was also after rotating the screen and flipping it to tablet mode. Model UN5401, AMD 6800H.

So, no "switch" event, or tablet mode callout.

Having done a lot of searching, it seems like this might be part of the "amd_sfh" module. I was also hoping to find a manual script for swapping to tablet mode, but it seems like that happens at a lower level, and relies on the `libinput` events.

I would love to report this upstream to the appropriate place to help debug, but I don't know where that would be. Can someone point me towards it?

**Comment by Buskebam** [comment]
Any luck finding the place where we should report/ try to fix this upstream? Having the same issue unfortunately.

**Comment by Sporknife** [comment]
This bug has been open for some time now. I hope it gets more attention.
https://bugzilla.kernel.org/show_bug.cgi?id=214675

**Comment by Buskebam** [comment]
We got an update

> AFAIK the issue rely on the fact that amd-sfh do not support lid angle sensors as of today, but I'm not sure if this laptop use that driver or ASUS has invented something else for handling it and therefore the driver is fully missing.

Not sure how we can continue our search towards the correct place to report a bug.

**Comment by Sporknife** [comment]
Found some documentation. Go to https://docs.kernel.org/admin-guide/abi-testing.html and search for ``/sys/bus/surface_aggregator/devices/01:0e:01:00:01/state``.

But as far as I understood, this is only for testing/debugging. I think.

**Comment by ldrahnik** [comment]
I developed a driver for laptop `Zenbook UN5401QAB` (AMD), `Vivobook TM420IA` (AMD) and other laptops with this problem https://github.com/asus-linux-drivers/asus-accel-tablet-mode-driver using accelerometer

**Comment by ldrahnik** [comment]
Closing as this issue is not related to this driver and exists mentioned [solution](https://github.com/asus-linux-drivers/asus-accel-tablet-mode-driver)

**Comment by ldrahnik** [comment]
Discussion continues [here](https://github.com/asus-linux-drivers/asus-accel-tablet-mode-driver/issues/2)

**Comment by ldrahnik** [comment]
> https://bugzilla.kernel.org/show_bug.cgi?id=214675
>
>--- Comment #15 from Tom (th.buskens@gmail.com) ---
>Could this patch be related to our problem.
>https://lkml.org/lkml/2025/4/24/973

The patch might be related.

**Comment by beankylla** [comment]
will it be integrated in the kernel or should we expect to have to apply a patch?
