### ISSUE TITLE
Cant Boot into Desktop after installation

### ISSUE THREAD

**Issue by Lamdarer** [asus-linux-drivers/asus-fliplock-driver#4]
I have an Asus VivoBook Flip 14 TM420UA and tried to install this on Manjaro Gnome after I had already successfully installed [numpad driver](https://github.com/asus-linux-drivers/asus-touchpad-numpad-driver)(so thx for the great work btw),
but unfortunately after I logged into my user account the screen would just stay black(though the mouse showed up for a few seconds) and when I tried to bring up the numpad it would turn off soon after it appeared. 

The only option I had left was to uninstall both drivers from the tty because just uninstalling the asus-fliplock-driver wasn't enough. 

Before that I also tried to uncomment the `# ExecStartPre=/bin/sleep 2` but this didnt help, though I only did that for the fliplock driver not the touchpad driver so I am not sure if this could have been the issue (also it worked before when I just had the numpad driver running).

What could I do to get this running?

**Comment by ldrahnik** [comment]
Hello,
thank you for creating an issue. At first, I have no idea. Check systemd logs or you maybe installed something else too. What seems to be wrong maybe is X11 service in NumberPad driver because driver is restarting when is laptop started so might help change service file to default service if it is your case = you use X11. Anyway I would start with reading service systemd log.

**Comment by Lamdarer** [comment]
Ok, thank you I will check if I can find anything, it might indeed be related to systemd since I also get an error which seems systemd related when I try to install the AUR package of the numpad driver.(also opened an issue there [#62](https://github.com/asus-linux-drivers/asus-touchpad-numpad-driver/issues/62) but since I could login again after uninstalling both with ./uninstall.sh and I am quite sure that I didnt install anything else when it first appeared I think that it is somehow linked to it)

**Comment by ldrahnik** [comment]
Unfortunately, I do not know how to debug/do progress with this issue atm. It can be reopened.

**Comment by ldrahnik** [comment]
@Lamdarer Please try the latest version and let me know.

**Comment by Lamdarer** [comment]
Thanks for the pointer, I tried it to but without avail.
Might try again and check a bit more into it(logs etc) if I have time.
Also I wasn't really able to update the `asus-touchpad-numpad-driver` it stooped working after git pull and than ./install.sh (I rolled back my system for now).

**Comment by ldrahnik** [comment]
@Lamdarer `asus-touchpad-numpad-driver` should be ok now

**Comment by Lamdarer** [comment]
Thank you it the `asus-touchpad-numpad-driver` works now after the update.
Just to report, the new behavior opens and closes the numpad driver when pressing the top right touchpad corner. And the swipe gesture closes the calculator, is that the intended behavior now? I think I selected yes for all questions of the installation.

**Comment by ldrahnik** [comment]
@Lamdarer Swipe gesture from top left now works only when is NumberPad activated and should toggle (first slide opens, second closes) calculator app by default for Elementary OS & Ubuntu `gnome calculator` and slide gesture from top right icon serve for fast enabling touchpad.
