### ISSUE TITLE
No asus_touchpad.service file to uncomment

### ISSUE THREAD

**Issue by aronoco** [asus-linux-drivers/asus-fliplock-driver#5]
I am not able to install due to boot failure on pop os. I could not find the asus_touchpad.service file that you reference in your directions.

**Comment by ldrahnik** [comment]
Hello,
thank you for creating an issue.

I fixed service filename in Readme. Anyway recommended line is already uncommented. Can you please add more details & logs about boot failure? I trust it is solvable :-)

**Comment by aronoco** [comment]
Sure! I logged into my recovery partition and, through it, uninstalled asus-fliplock-driver. This fixed my boot failure (thank the gods). I am running pop os on an ASUS ZenBook Flip 15. 

I am looking at my boot log but I don't know what to specifically to send. I never really studied computer programming in detail and don't want to send any compromising material that might come up in the log. What should I send?

**Comment by ldrahnik** [comment]
Run this command `sudo systemctl start asus_fliplock` and check driver service started by status command `sudo systemctl status asus_fliplock`. Post results.

**Comment by ldrahnik** [comment]
Can you also please confirm it happens on clear system Pop OS? And which version? Use / I could debug that via Live USB with your system in case it is not specific problem to your configuration (in other words everyone on Pop OS has the same problem).

**Comment by ldrahnik** [comment]
Closed for issue owner inactivity, can be reopened.
