### ISSUE TITLE
Could you make it work with model ‎UN5401RA-DB74T

### ISSUE THREAD

**Issue by ritchiedalto** [asus-linux-drivers/asus-fliplock-driver#6]
It currently doesn't light up the Numpad, but it does turn it on such that it will type numbers, you just can see what you're pressing.

ASUS Zenbook 14 Flip

https://www.amazon.com/dp/B0B6FZT32J?ref=ppx_yo2ov_dt_b_product_details&th=1

**Comment by ldrahnik** [comment]
@ritchiedalto Hello, thank you for creating an issue. 

Do you mean situation when is installed driver from this organization for NumberPad and NumberPad is then activated and then is done flip to tablet mode with laptop with installed this driver too?

**Comment by ritchiedalto** [comment]
I'm not 100% certain I understand your question. But the symptom is that I touch the hotspot on the glide pad that should  light up the numpad grid on the glide pad. But it does not light up, however it is in fact in numpad mode when you touch it.

As far as flipping, the [asus-fliplock-driver](https://github.com/asus-linux-drivers/asus-fliplock-driver) don't work on this model either.

**Comment by ldrahnik** [comment]
@ritchiedalto 

If is anything related (without any association to fliplock) to the NumberPad driver, please create an issue in the corresponding [repository](https://github.com/asus-linux-drivers/asus-touchpad-numpad-driver).

About flipping, can you please exclude that you do not have AMD? As was mentioned in [this issue](https://github.com/asus-linux-drivers/asus-fliplock-driver/issues/3). For this driver working you should be able see flipping events as is in that issue described during running command `sudo libinput debug-events`. Without any events is not possible for this driver hook on them and do something. Also please run and attach the result of `LOG=DEBUG sudo -E ./asus_fliplock.py`.

**Comment by ldrahnik** [comment]
@ritchiedalto Closed for inactivity of issue owner. Can be reopened.
